language: python

# align the env's and the python's; below "$PY27 ||" will not be run on py26,
# and "$PY27 &&" will only be run on py26.
matrix:
  include:
    - python: "2.6"
      env: PY27=false
    - python: "2.7"
      env: PY27=true


install:
  - pip install -e .[test]
  - pip install coveralls
  - pip install tox
  - pip freeze

script:
  if $PY27; then tox -e py27; else tox -e py26; fi

after_success:
  # only get coverage on python-2.7
  - $PY27 && coveralls --rcfile coveragerc
